### ISSUE TITLE
Can't connect via the api while blink1Control is running

### ISSUE THREAD

**Issue by Qazzian** [sandeepmistry/node-blink1#27]
So I was just experimenting with the node api for the blink and I kept getting the error message:

```
Error: cannot open device with path USB_27b8_01ed_14100000
    at Error (native)
    at new HID (./node_modules/node-hid/nodehid.js:28:14)
    at new Blink1 (./node_modules/node-blink1/blink1.js:49:20)
    (etc)
```

Spent ages looking for answers on node-hid and re-compiling node-gyp etc.

Turns out, you can't access the device while the blink control app is running.

Just thought I'd document it so no one else falls down the same pit as me.

**Comment by sandeepmistry** [comment]
@Qazzian thanks for the info. I've added a note in e3d62cd5e902d3ab67a40dc93e7962a1abfc755f about this. Please submit a pull request if you think anything needs to be added/changed.
